name: Test

on:
  push:
    branches: [ "master" ]
    paths:
      - "redbaby/**"
      - "tests/**"
      - "setup.py"
      - "requirements.txt"
      - "requirements-test.txt"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "redbaby/**"
      - "tests/**"
      - "setup.py"
      - "requirements.txt"
      - "requirements-test.txt"
      - ".github/workflows/test.yml"


jobs:
  autotester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-test.txt
      - name: Setup pip and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Install
        run: |
          pip install .
      - name: Test.
        working-directory: .
        run: pytest ./tests/ --tb=line --show-capture=no
